# Generated by Django 3.2.4 on 2021-08-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_bio_user_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legal',
            field=models.BooleanField(default=False),
        ),
    ]
