# Generated by Django 3.2.4 on 2021-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biografia',
        ),
        migrations.AddField(
            model_name='user',
            name='Pacote',
            field=models.CharField(choices=[('Pacote Kamba', 'Kamba'), ('Pacote Garra', 'Garra')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
