# Generated by Django 4.1.1 on 2022-12-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210830_1540"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="legal", new_name="verificado",
        ),
        migrations.RemoveField(model_name="user", name="Pacote",),
        migrations.AddField(
            model_name="user",
            name="Nivel",
            field=models.CharField(
                choices=[
                    ("Tecnico de Manutençao", "tec"),
                    ("CEO", "ceo"),
                    ("Funcionario", "funcionario"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="Telefone",
            field=models.CharField(default=1, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="bi",
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="foto",
            field=models.ImageField(default=1, upload_to=None, verbose_name=""),
            preserve_default=False,
        ),
    ]
