# Generated by Django 4.1.5 on 2023-01-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, upload_to='static/media/img', verbose_name=''),
        ),
    ]
