# Generated by Django 4.1.5 on 2023-01-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_telefone_alter_user_bi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Telefone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='bi',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
