# Generated by Django 4.1.5 on 2023-01-14 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(blank=True, upload_to='static/media/img', verbose_name='')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categoria',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='serie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(blank=True, upload_to='static/media/img', verbose_name='')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'serie',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('img1', models.ImageField(blank=True, upload_to='static/media/img', verbose_name='img')),
                ('img2', models.ImageField(blank=True, upload_to='static/media/img', verbose_name='img')),
                ('img3', models.ImageField(blank=True, upload_to='static/media/img', verbose_name='img')),
                ('img4', models.ImageField(blank=True, upload_to='static/media/img', verbose_name='img')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=5000000, verbose_name='Descrição')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('preco', models.IntegerField(verbose_name='preco')),
                ('prestacoes', models.IntegerField(verbose_name='prestacoes')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.categoria', verbose_name='categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'produto',
                'ordering': ['-createdAt'],
            },
        ),
    ]
