# Generated by Django 4.1.5 on 2023-01-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='number',
            field=models.IntegerField(auto_created=True, blank=True),
        ),
    ]
